services:
  mongo:
    container_name: docker-mern-mongo
    image: mongo:latest
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    # build:
    #   context: ./database
    # container_name: docker-mern-mongo
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - app
      
  backend:
    container_name: docker-mern-backend
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    restart: always
    networks:
      - app

  frontend:
    container_name: docker-mern-frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/usr/src/frontend
      - frontend_node_modules:/usr/src/frontend/node_modules/
    depends_on:
      - backend
    restart: always
    networks:
      - app

  nginx:
    container_name: nginx_server
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - '/etc/letsencrypt:/etc/letsencrypt'
    depends_on:
      - mongo
      - backend
      - frontend
    restart: always
    networks:
      - app

volumes:
  mongo_data:
  frontend_node_modules:

networks:
  app:
    driver: bridge